name: test_django
on: [push]
jobs:
  kodjaz:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10.7'
          cache: 'pip'
          cache-dependency-path: '**/requirements_dev.txt'
      - name: Install dependencies
        run: pip install -r requirements/requirements_dev.txt # install all our dependencies for the project
      - run: pytest .
