name: test_django
on: [push]
jobs:
  kodjaz:
    runs-on: ubuntu-latest
    # Service containers to run with `kodjaz`
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10.7'
          cache: 'pip'
          cache-dependency-path: '**/requirements_dev.txt'
      - name: Install PostgreSQL client
        run: |
          apt-get update
          apt-get install --yes postgresql-client

      - name: Query database
        run: psql -h postgres -d postgres -U postgres -c 'SELECT 1;'
        env:
          # The hostname used to communicate with the PostgreSQL service container
          PGPASSWORD: postgres
          POSTGRES_PORT: 5432
      - name: Install dependencies
        run: pip install -r requirements/requirements_dev.txt # install all our dependencies for the project
      - name: Create a dummy env fille
        run: cp env_template .env
      - run: python manage.py test
